joy_node:
  auto_repeat_rate: 30
  coalesce_interval: 0.0333
  deadzone: 0.01

servos:
  pwm_frequency: 50
  throttle:
    channel: 0
    center: 320
    direction: 1
    range: 100
  steering:
    channel: 1
    center: 325
    direction: 1
    range: 180

teleop:
  drive:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: donkey/drive
    axis_mappings:
      - axis: 1
        target: linear.x
        scale: 1.0
      - axis: 3
        target: angular.z
        scale: 1.0
  record:
    type: topic
    message_type: std_msgs/Bool
    topic_name: donkey/record
    axis_mappings:
      - button: 4
        target: data
